// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuL14wS7aaTkOcUxm2AkdVGnkNDB1lWqQ',
    appId: '1:391270885453:web:05285827d9829576871404',
    messagingSenderId: '391270885453',
    projectId: 'whatsapp-clone-1247d',
    authDomain: 'whatsapp-clone-1247d.firebaseapp.com',
    storageBucket: 'whatsapp-clone-1247d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Vivylf9aym5eSjjyn14oNCmuiXpkwss',
    appId: '1:391270885453:android:7f7a519a3615d6cd871404',
    messagingSenderId: '391270885453',
    projectId: 'whatsapp-clone-1247d',
    storageBucket: 'whatsapp-clone-1247d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZn2wm8lDKvmJBfxaoypYirSipunwxBt0',
    appId: '1:391270885453:ios:644cebb3464d8305871404',
    messagingSenderId: '391270885453',
    projectId: 'whatsapp-clone-1247d',
    storageBucket: 'whatsapp-clone-1247d.appspot.com',
    androidClientId: '391270885453-nb0lnbi663g84br0ofsuqhtj4didjtj6.apps.googleusercontent.com',
    iosClientId: '391270885453-8tt64enah2jobktr81bjep28ng9m9spv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
